In [1]:
#Question No:- 1  Dataset:- forestfire.csv
#Classify the size_Categorie of the burned area of the forest ( Small , Large) by using SVM classification

In [2]:
#Applying the feature selection engineering concepts to find out most important feature for build the SVM model

####Univariate feature selection

In [3]:
#Feature Extraction with Univariate Statistical Tests (Chi-squared for classification)
import pandas as pd
from pandas import read_csv
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
#load data
filename = 'forestfires.csv'
names = ['month','day','FFMC','DMC','DC','ISI','temp','RH','wind','rain','area','dayfri','daymon','daysat',
         'daysun','daythu','daytue','daywed','monthapr','monthaug','monthdec','monthfeb','monthjan','monthjul',
         'monthjun','monthmar','monthmay','monthnov','monthoct','monthsep','size_category']
dataframe = read_csv(filename, names=names, header=0)
dataframe


month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain  ...  monthfeb  \
0     mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0  ...         0   
1     oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0  ...         0   
2     oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0  ...         0   
3     mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2  ...         0   
4     mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0  ...         0   
..    ...  ...   ...    ...    ...   ...   ...  ..   ...   ...  ...       ...   
512   aug  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0  ...         0   
513   aug  sun  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  ...         0   
514   aug  sun  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  ...         0   
515   aug  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0  ...         0   
516   nov  tue  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0  ...         0   

     monthjan  monthjul  monthjun  monthmar  monthmay  monthnov  monthoct  \
0           0         0         0         1         0         0         0   
1           0         0         0         0         0         0         1   
2           0         0         0         0         0         0         1   
3           0         0         0         1         0         0         0   
4           0         0         0         1         0         0         0   
..        ...       ...       ...       ...       ...       ...       ...   
512         0         0         0         0         0         0         0   
513         0         0         0         0         0         0         0   
514         0         0         0         0         0         0         0   
515         0         0         0         0         0         0         0   
516         0         0         0         0         0         1         0   

     monthsep  size_category  
0           0          small  
1           0          small  
2           0          small  
3           0          small  
4           0          small  
..        ...            ...  
512         0          large  
513         0          large  
514         0          large  
515         0          small  
516         0          small  

[517 rows x 31 columns]

In [4]:
dataframe.dtypes 

month             object
day               object
FFMC             float64
DMC              float64
DC               float64
ISI              float64
temp             float64
RH                 int64
wind             float64
rain             float64
area             float64
dayfri             int64
daymon             int64
daysat             int64
daysun             int64
daythu             int64
daytue             int64
daywed             int64
monthapr           int64
monthaug           int64
monthdec           int64
monthfeb           int64
monthjan           int64
monthjul           int64
monthjun           int64
monthmar           int64
monthmay           int64
monthnov           int64
monthoct           int64
monthsep           int64
size_category     object
dtype: object

In [5]:
dataframe[['month','day','size_category']]= dataframe[['month','day','size_category']].apply(lambda x: pd.factorize(x) [0])

In [6]:
dataframe

month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain  ...  \
0        0    0  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0  ...   
1        1    1  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0  ...   
2        1    2  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0  ...   
3        0    0  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2  ...   
4        0    3  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0  ...   
..     ...  ...   ...    ...    ...   ...   ...  ..   ...   ...  ...   
512      2    3  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0  ...   
513      2    3  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  ...   
514      2    3  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  ...   
515      2    2  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0  ...   
516     11    1  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0  ...   

     monthfeb  monthjan  monthjul  monthjun  monthmar  monthmay  monthnov  \
0           0         0         0         0         1         0         0   
1           0         0         0         0         0         0         0   
2           0         0         0         0         0         0         0   
3           0         0         0         0         1         0         0   
4           0         0         0         0         1         0         0   
..        ...       ...       ...       ...       ...       ...       ...   
512         0         0         0         0         0         0         0   
513         0         0         0         0         0         0         0   
514         0         0         0         0         0         0         0   
515         0         0         0         0         0         0         0   
516         0         0         0         0         0         0         1   

     monthoct  monthsep  size_category  
0           0         0              0  
1           1         0              0  
2           1         0              0  
3           0         0              0  
4           0         0              0  
..        ...       ...            ...  
512         0         0              1  
513         0         0              1  
514         0         0              1  
515         0         0              0  
516         0         0              0  

[517 rows x 31 columns]

In [7]:
X=dataframe.iloc[:,0:-1] 
X 

month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain  ...  \
0        0    0  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0  ...   
1        1    1  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0  ...   
2        1    2  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0  ...   
3        0    0  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2  ...   
4        0    3  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0  ...   
..     ...  ...   ...    ...    ...   ...   ...  ..   ...   ...  ...   
512      2    3  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0  ...   
513      2    3  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  ...   
514      2    3  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  ...   
515      2    2  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0  ...   
516     11    1  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0  ...   

     monthdec  monthfeb  monthjan  monthjul  monthjun  monthmar  monthmay  \
0           0         0         0         0         0         1         0   
1           0         0         0         0         0         0         0   
2           0         0         0         0         0         0         0   
3           0         0         0         0         0         1         0   
4           0         0         0         0         0         1         0   
..        ...       ...       ...       ...       ...       ...       ...   
512         0         0         0         0         0         0         0   
513         0         0         0         0         0         0         0   
514         0         0         0         0         0         0         0   
515         0         0         0         0         0         0         0   
516         0         0         0         0         0         0         0   

     monthnov  monthoct  monthsep  
0           0         0         0  
1           0         1         0  
2           0         1         0  
3           0         0         0  
4           0         0         0  
..        ...       ...       ...  
512         0         0         0  
513         0         0         0  
514         0         0         0  
515         0         0         0  
516         1         0         0  

[517 rows x 30 columns]

In [8]:
Y = dataframe.iloc[:,-1] 
Y

0      0
1      0
2      0
3      0
4      0
      ..
512    1
513    1
514    1
515    0
516    0
Name: size_category, Length: 517, dtype: int64

In [9]:
#feature extraction
test = SelectKBest(score_func=chi2, k=4)
fit = test.fit(X, Y)
#summarize scores
set_printoptions(precision=3)
print(fit.scores_)
features = fit.transform(X)


#For regression: f_regression, mutual_info_regression
#For classification: chi2, f_classif, mutual_info_classif

[7.301e+00 1.085e+00 8.443e-02 2.301e+01 2.187e+01 9.054e-02 3.339e-02
 6.350e+00 1.441e+00 5.216e+00 1.577e+04 2.055e-01 5.513e-02 7.066e-01
 1.139e-01 9.643e-01 6.201e-01 2.172e-01 9.958e-02 1.157e+00 1.760e+01
 9.867e-02 7.354e-01 2.499e-02 7.382e-01 5.975e-01 5.436e-01 3.677e-01
 3.667e-04 6.691e-01]


#### Recursive Feature Elimination

In [10]:
#Feature Extraction with RFE
from pandas import read_csv
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
#load data
filename = 'forestfires.csv'
names = ['month','day','FFMC','DMC','DC','ISI','temp','RH','wind','rain','area','dayfri','daymon','daysat',
         'daysun','daythu','daytue','daywed','monthapr','monthaug','monthdec','monthfeb','monthjan','monthjul',
         'monthjun','monthmar','monthmay','monthnov','monthoct','monthsep','size_category']
dataframe = read_csv(filename, names=names, header=0)


In [11]:
dataframe[['month','day','size_category']]= dataframe[['month','day','size_category']].apply(lambda x: pd.factorize(x) [0])

In [12]:
dataframe

month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain  ...  \
0        0    0  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0  ...   
1        1    1  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0  ...   
2        1    2  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0  ...   
3        0    0  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2  ...   
4        0    3  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0  ...   
..     ...  ...   ...    ...    ...   ...   ...  ..   ...   ...  ...   
512      2    3  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0  ...   
513      2    3  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  ...   
514      2    3  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  ...   
515      2    2  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0  ...   
516     11    1  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0  ...   

     monthfeb  monthjan  monthjul  monthjun  monthmar  monthmay  monthnov  \
0           0         0         0         0         1         0         0   
1           0         0         0         0         0         0         0   
2           0         0         0         0         0         0         0   
3           0         0         0         0         1         0         0   
4           0         0         0         0         1         0         0   
..        ...       ...       ...       ...       ...       ...       ...   
512         0         0         0         0         0         0         0   
513         0         0         0         0         0         0         0   
514         0         0         0         0         0         0         0   
515         0         0         0         0         0         0         0   
516         0         0         0         0         0         0         1   

     monthoct  monthsep  size_category  
0           0         0              0  
1           1         0              0  
2           1         0              0  
3           0         0              0  
4           0         0              0  
..        ...       ...            ...  
512         0         0              1  
513         0         0              1  
514         0         0              1  
515         0         0              0  
516         0         0              0  

[517 rows x 31 columns]

In [13]:
X=dataframe.iloc[:,0:-1] 
X 

month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain  ...  \
0        0    0  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0  ...   
1        1    1  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0  ...   
2        1    2  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0  ...   
3        0    0  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2  ...   
4        0    3  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0  ...   
..     ...  ...   ...    ...    ...   ...   ...  ..   ...   ...  ...   
512      2    3  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0  ...   
513      2    3  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  ...   
514      2    3  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  ...   
515      2    2  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0  ...   
516     11    1  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0  ...   

     monthdec  monthfeb  monthjan  monthjul  monthjun  monthmar  monthmay  \
0           0         0         0         0         0         1         0   
1           0         0         0         0         0         0         0   
2           0         0         0         0         0         0         0   
3           0         0         0         0         0         1         0   
4           0         0         0         0         0         1         0   
..        ...       ...       ...       ...       ...       ...       ...   
512         0         0         0         0         0         0         0   
513         0         0         0         0         0         0         0   
514         0         0         0         0         0         0         0   
515         0         0         0         0         0         0         0   
516         0         0         0         0         0         0         0   

     monthnov  monthoct  monthsep  
0           0         0         0  
1           0         1         0  
2           0         1         0  
3           0         0         0  
4           0         0         0  
..        ...       ...       ...  
512         0         0         0  
513         0         0         0  
514         0         0         0  
515         0         0         0  
516         1         0         0  

[517 rows x 30 columns]

In [14]:
Y = dataframe.iloc[:,-1] 
Y

0      0
1      0
2      0
3      0
4      0
      ..
512    1
513    1
514    1
515    0
516    0
Name: size_category, Length: 517, dtype: int64

In [15]:
#feature extraction
model = LogisticRegression(max_iter=400)
rfe = RFE(model)
fit = rfe.fit(X, Y)
import matplotlib.pyplot as plt
plt.show()


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


In [16]:
#Num Features: 
fit.n_features_

15

In [17]:
#Selected Features:
fit.support_

array([False, False,  True, False, False,  True, False, False, False,
       False,  True,  True, False,  True,  True,  True,  True,  True,
       False, False,  True,  True, False,  True, False,  True, False,
       False,  True,  True])

In [18]:
#Feature Ranking:
fit.ranking_

array([ 7,  5,  1, 11, 13,  1,  2,  3, 12, 14,  1,  1,  4,  1,  1,  1,  1,
        1,  8,  6,  1,  1, 10,  1,  9,  1, 15, 16,  1,  1])

#### Feature Importance using Decision Tree

In [19]:
#Feature Importance with Extra Trees Classifier
from pandas import read_csv
from sklearn.tree import  DecisionTreeClassifier
#load data
filename = 'forestfires.csv'
names = ['month','day','FFMC','DMC','DC','ISI','temp','RH','wind','rain','area','dayfri','daymon','daysat',
         'daysun','daythu','daytue','daywed','monthapr','monthaug','monthdec','monthfeb','monthjan','monthjul',
         'monthjun','monthmar','monthmay','monthnov','monthoct','monthsep','size_category']
dataframe = read_csv(filename, names=names, header=0)

In [20]:
dataframe[['month','day','size_category']]= dataframe[['month','day','size_category']].apply(lambda x: pd.factorize(x) [0])

In [21]:
dataframe

month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain  ...  \
0        0    0  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0  ...   
1        1    1  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0  ...   
2        1    2  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0  ...   
3        0    0  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2  ...   
4        0    3  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0  ...   
..     ...  ...   ...    ...    ...   ...   ...  ..   ...   ...  ...   
512      2    3  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0  ...   
513      2    3  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  ...   
514      2    3  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  ...   
515      2    2  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0  ...   
516     11    1  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0  ...   

     monthfeb  monthjan  monthjul  monthjun  monthmar  monthmay  monthnov  \
0           0         0         0         0         1         0         0   
1           0         0         0         0         0         0         0   
2           0         0         0         0         0         0         0   
3           0         0         0         0         1         0         0   
4           0         0         0         0         1         0         0   
..        ...       ...       ...       ...       ...       ...       ...   
512         0         0         0         0         0         0         0   
513         0         0         0         0         0         0         0   
514         0         0         0         0         0         0         0   
515         0         0         0         0         0         0         0   
516         0         0         0         0         0         0         1   

     monthoct  monthsep  size_category  
0           0         0              0  
1           1         0              0  
2           1         0              0  
3           0         0              0  
4           0         0              0  
..        ...       ...            ...  
512         0         0              1  
513         0         0              1  
514         0         0              1  
515         0         0              0  
516         0         0              0  

[517 rows x 31 columns]

In [22]:
X=dataframe.iloc[:,0:-1] 
X 

month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain  ...  \
0        0    0  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0  ...   
1        1    1  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0  ...   
2        1    2  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0  ...   
3        0    0  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2  ...   
4        0    3  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0  ...   
..     ...  ...   ...    ...    ...   ...   ...  ..   ...   ...  ...   
512      2    3  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0  ...   
513      2    3  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  ...   
514      2    3  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  ...   
515      2    2  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0  ...   
516     11    1  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0  ...   

     monthdec  monthfeb  monthjan  monthjul  monthjun  monthmar  monthmay  \
0           0         0         0         0         0         1         0   
1           0         0         0         0         0         0         0   
2           0         0         0         0         0         0         0   
3           0         0         0         0         0         1         0   
4           0         0         0         0         0         1         0   
..        ...       ...       ...       ...       ...       ...       ...   
512         0         0         0         0         0         0         0   
513         0         0         0         0         0         0         0   
514         0         0         0         0         0         0         0   
515         0         0         0         0         0         0         0   
516         0         0         0         0         0         0         0   

     monthnov  monthoct  monthsep  
0           0         0         0  
1           0         1         0  
2           0         1         0  
3           0         0         0  
4           0         0         0  
..        ...       ...       ...  
512         0         0         0  
513         0         0         0  
514         0         0         0  
515         0         0         0  
516         1         0         0  

[517 rows x 30 columns]

In [23]:
Y = dataframe.iloc[:,-1] 
Y

0      0
1      0
2      0
3      0
4      0
      ..
512    1
513    1
514    1
515    0
516    0
Name: size_category, Length: 517, dtype: int64

In [24]:
#feature extraction
model = DecisionTreeClassifier()
model.fit(X, Y)
print(model.feature_importances_)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]


####Start build a SVM model on dataset by using important feature 

In [25]:
#Import important libraries that we have reqired while building model
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn import svm
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split, cross_val_score

In [126]:
#load data
filename = 'forestfires.csv'
names = ['month','RH','DC','DMC','area','size_category']
dataframe = read_csv(filename, names=names, header=0)

In [127]:
#Convert data from categrical into numerical 
dataframe[['size_category']]= dataframe[['size_category']].apply(lambda x: pd.factorize(x) [0])

In [128]:
dataframe

month  \
mar fri 86.2 26.2  94.3  5.1  8.2  51 6.7 0.0 0.00  1 0 0 0 0 0 0 0 0 0 0 0 0 0      1   
oct tue 90.6 35.4  669.1 6.7  18.0 33 0.9 0.0 0.00  0 0 0 0 0 1 0 0 0 0 0 0 0 0      0   
    sat 90.6 43.7  686.9 6.7  14.6 33 1.3 0.0 0.00  0 0 1 0 0 0 0 0 0 0 0 0 0 0      0   
mar fri 91.7 33.3  77.5  9.0  8.3  97 4.0 0.2 0.00  1 0 0 0 0 0 0 0 0 0 0 0 0 0      1   
    sun 89.3 51.3  102.2 9.6  11.4 99 1.8 0.0 0.00  0 0 0 1 0 0 0 0 0 0 0 0 0 0      1   
...                                                                                ...   
aug sun 81.6 56.7  665.6 1.9  27.8 32 2.7 0.0 6.44  0 0 0 1 0 0 0 0 1 0 0 0 0 0      0   
                              21.9 71 5.8 0.0 54.29 0 0 0 1 0 0 0 0 1 0 0 0 0 0      0   
                              21.2 70 6.7 0.0 11.16 0 0 0 1 0 0 0 0 1 0 0 0 0 0      0   
    sat 94.4 146.0 614.7 11.3 25.6 42 4.0 0.0 0.00  0 0 1 0 0 0 0 0 1 0 0 0 0 0      0   
nov tue 79.5 3.0   106.7 1.1  11.8 31 4.5 0.0 0.00  0 0 0 0 0 1 0 0 0 0 0 0 0 0      0   

                                                                                 RH  \
mar fri 86.2 26.2  94.3  5.1  8.2  51 6.7 0.0 0.00  1 0 0 0 0 0 0 0 0 0 0 0 0 0   0   
oct tue 90.6 35.4  669.1 6.7  18.0 33 0.9 0.0 0.00  0 0 0 0 0 1 0 0 0 0 0 0 0 0   0   
    sat 90.6 43.7  686.9 6.7  14.6 33 1.3 0.0 0.00  0 0 1 0 0 0 0 0 0 0 0 0 0 0   0   
mar fri 91.7 33.3  77.5  9.0  8.3  97 4.0 0.2 0.00  1 0 0 0 0 0 0 0 0 0 0 0 0 0   0   
    sun 89.3 51.3  102.2 9.6  11.4 99 1.8 0.0 0.00  0 0 0 1 0 0 0 0 0 0 0 0 0 0   0   
...                                                                              ..   
aug sun 81.6 56.7  665.6 1.9  27.8 32 2.7 0.0 6.44  0 0 0 1 0 0 0 0 1 0 0 0 0 0   0   
                              21.9 71 5.8 0.0 54.29 0 0 0 1 0 0 0 0 1 0 0 0 0 0   0   
                              21.2 70 6.7 0.0 11.16 0 0 0 1 0 0 0 0 1 0 0 0 0 0   0   
    sat 94.4 146.0 614.7 11.3 25.6 42 4.0 0.0 0.00  0 0 1 0 0 0 0 0 1 0 0 0 0 0   0   
nov tue 79.5 3.0   106.7 1.1  11.8 31 4.5 0.0 0.00  0 0 0 0 0 1 0 0 0 0 0 0 0 0   0   

                                                                                 DC  \
mar fri 86.2 26.2  94.3  5.1  8.2  51 6.7 0.0 0.00  1 0 0 0 0 0 0 0 0 0 0 0 0 0   0   
oct tue 90.6 35.4  669.1 6.7  18.0 33 0.9 0.0 0.00  0 0 0 0 0 1 0 0 0 0 0 0 0 0   0   
    sat 90.6 43.7  686.9 6.7  14.6 33 1.3 0.0 0.00  0 0 1 0 0 0 0 0 0 0 0 0 0 0   0   
mar fri 91.7 33.3  77.5  9.0  8.3  97 4.0 0.2 0.00  1 0 0 0 0 0 0 0 0 0 0 0 0 0   0   
    sun 89.3 51.3  102.2 9.6  11.4 99 1.8 0.0 0.00  0 0 0 1 0 0 0 0 0 0 0 0 0 0   0   
...                                                                              ..   
aug sun 81.6 56.7  665.6 1.9  27.8 32 2.7 0.0 6.44  0 0 0 1 0 0 0 0 1 0 0 0 0 0   0   
                              21.9 71 5.8 0.0 54.29 0 0 0 1 0 0 0 0 1 0 0 0 0 0   0   
                              21.2 70 6.7 0.0 11.16 0 0 0 1 0 0 0 0 1 0 0 0 0 0   0   
    sat 94.4 146.0 614.7 11.3 25.6 42 4.0 0.0 0.00  0 0 1 0 0 0 0 0 1 0 0 0 0 0   0   
nov tue 79.5 3.0   106.7 1.1  11.8 31 4.5 0.0 0.00  0 0 0 0 0 1 0 0 0 0 0 0 0 0   1   

                                                                                 DMC  \
mar fri 86.2 26.2  94.3  5.1  8.2  51 6.7 0.0 0.00  1 0 0 0 0 0 0 0 0 0 0 0 0 0    0   
oct tue 90.6 35.4  669.1 6.7  18.0 33 0.9 0.0 0.00  0 0 0 0 0 1 0 0 0 0 0 0 0 0    1   
    sat 90.6 43.7  686.9 6.7  14.6 33 1.3 0.0 0.00  0 0 1 0 0 0 0 0 0 0 0 0 0 0    1   
mar fri 91.7 33.3  77.5  9.0  8.3  97 4.0 0.2 0.00  1 0 0 0 0 0 0 0 0 0 0 0 0 0    0   
    sun 89.3 51.3  102.2 9.6  11.4 99 1.8 0.0 0.00  0 0 0 1 0 0 0 0 0 0 0 0 0 0    0   
...                                                                              ...   
aug sun 81.6 56.7  665.6 1.9  27.8 32 2.7 0.0 6.44  0 0 0 1 0 0 0 0 1 0 0 0 0 0    0   
                              21.9 71 5.8 0.0 54.29 0 0 0 1 0 0 0 0 1 0 0 0 0 0    0   
                              21.2 70 6.7 0.0 11.16 0 0 0 1 0 0 0 0 1 0 0 0 0 0    0   
    sat 94.4 146.0 614.7 11.3 

In [129]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 517 entries, ('mar', 'fri', 86.2, 26.2, 94.3, 5.1, 8.2, 51, 6.7, 0.0, 0.0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0) to ('nov', 'tue', 79.5, 3.0, 106.7, 1.1, 11.8, 31, 4.5, 0.0, 0.0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0)
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   month          517 non-null    int64
 1   RH             517 non-null    int64
 2   DC             517 non-null    int64
 3   DMC            517 non-null    int64
 4   area           517 non-null    int64
 5   size_category  517 non-null    int64
dtypes: int64(6)
memory usage: 90.5+ KB


In [132]:
array = dataframe.values
X = array[:,0:-1]
Y = array[:,-1]

In [133]:
X

array([[1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0],
       ...,
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0]])

In [135]:
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,

In [136]:
from sklearn.model_selection import train_test_split, cross_val_score
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size = 0.3)

In [120]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((361, 4), (361,), (156, 4), (156,))

####Grid Search CV

In [138]:
#Build a Support Vector Classification model on dataset using kernel= Radial Basis Function(rbf)
from sklearn.svm import SVC
#Find out the best values by using GridSearchCV
#a) gamma(control the influence of new feature mean how much you want the influence of new feature on the data); 
#gamma= higher value[ more influence of that new feature will have on the decision boundary, our model will slowly become from leberal to conservative model= means model have a more controll on the data(more penalty SVM get when it makes missclassification) & it will be less soft margin], 
#gamma= lower value[ less influence of new feature on decision boundary, liberal model= means free model it will tolerate anything (very less penalty SVM get when it makes missclassification)& it will be more soft margin]
#New feature= distance between observations & centre
#Soft margin:- it allows few observation which has made missclassify wrongly
#b)Cost['C'] or Penalty term
from sklearn.model_selection import GridSearchCV
clf = SVC()
param_grid = [{'kernel':['rbf'],'gamma':[50,5,10,0.5],'C':[15,14,13,12,11,10,0.1,0.001] }]
gsv = GridSearchCV(clf,param_grid,cv=10)
gsv.fit(X_train,y_train)

GridSearchCV(cv=10, estimator=SVC(),
             param_grid=[{'C': [15, 14, 13, 12, 11, 10, 0.1, 0.001],
                          'gamma': [50, 5, 10, 0.5], 'kernel': ['rbf']}])

In [139]:
#We have got best 'C', gamma values with model accuracy; if working with kernel is (rbf)
gsv.best_params_ , gsv.best_score_ 

({'C': 0.1, 'gamma': 50, 'kernel': 'rbf'}, 0.7091591591591591)

In [141]:
#I want to build a SVC model with C=0.1, gamma=50 & kernel= rbf
from sklearn.metrics import accuracy_score, confusion_matrix
clf = SVC(C= 0.1, gamma = 50, kernel= "rbf")
clf.fit(X_train , y_train)
y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(y_test, y_pred)

Accuracy = 78.2051282051282


array([[122,   0],
       [ 34,   0]])

In [142]:
#kernel= linear
clf = SVC(kernel= "linear") 
clf.fit(X_train , y_train)
y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(y_test, y_pred)    

Accuracy = 78.2051282051282


array([[122,   0],
       [ 34,   0]])

In [143]:
#kernel= polynomial
clf = SVC(kernel= "poly") 
clf.fit(X_train , y_train)
y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(y_test, y_pred) 

Accuracy = 78.2051282051282


array([[122,   0],
       [ 34,   0]])